///*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
// */
//package com.GUIPackage;
//
//import com.courseclass.Course;
//import com.userclass.Student;
//import com.userclass.Teacher;
//import java.util.*;
//import javax.swing.*;
//import java.awt.*;
//
///**
// *
// * @author adrian
// */
//public class HomePage extends javax.swing.JFrame {
//
//    /**
//     * Creates new form HomePage
//     */ 
//  public HomePage() {
//        
//        initComponents();
//        Course.init_Course(); // Ensure courses are initialized before accessing them
//        populateCourseList();  // Populate the CourseList panel with course names
//        JFrame frame = new JFrame("Wirexam");
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        frame.setSize(500, 300);
//        frame.setLayout(new BorderLayout());
//        
//         JPanel headerPanel = new JPanel();
//        headerPanel.setBackground(new Color(0, 102, 204));
//        headerPanel.setPreferredSize(new Dimension(0, 50));
//        JLabel title = new JLabel("Wirexam");
//        title.setFont(new Font("Arial", Font.BOLD, 20));
//        title.setForeground(Color.BLACK);
//        headerPanel.add(title);
//         JPanel sidebarPanel = new JPanel();
//        sidebarPanel.setBackground(new Color(0, 51, 102));
//        sidebarPanel.setPreferredSize(new Dimension(100, 0));
//
//        // Content Panel
//        JPanel contentPanel = new JPanel(new BorderLayout());
//        JTextArea textArea = new JTextArea();
//        textArea.setEditable(false);
//        textArea.setText("Matematika\nKIMIA\nBING");
//
//        // Input Panel di sebelah kanan
//        JPanel inputPanel = new JPanel(new BorderLayout());
//        inputPanel.setBackground(Color.LIGHT_GRAY);
//        JTextField inputField = new JTextField(20);
//        inputPanel.add(inputField, BorderLayout.NORTH);
//
//        // Menambahkan ke JFrame
//        frame.add(headerPanel, BorderLayout.NORTH);
//        frame.add(sidebarPanel, BorderLayout.WEST);
//        frame.add(contentPanel, BorderLayout.CENTER);
//        frame.add(inputPanel, BorderLayout.EAST);
//        contentPanel.add(new JScrollPane(textArea), BorderLayout.CENTER);
//
//        // Menampilkan JFrame
//        frame.setVisible(true);
//    
//    }
//
//    // Method to dynamically populate the CourseList panel
//    private void populateCourseList() {
//            // Clear the current content of the panel
//    CourseList.removeAll();
//
//    // Set a layout manager for the CourseList panel (BoxLayout for vertical stacking)
//    CourseList.setLayout(new BoxLayout(CourseList, BoxLayout.Y_AXIS));
//
//    // Iterate over the courses in Course.arrCourse and add them as JLabels
//    Color[] colors = {Color.RED, Color.BLUE, Color.GREEN, Color.ORANGE};
//    ArrayList<JLabel> labele = new ArrayList<>();
//    for (Course course : Course.getArrCourse()) {
//        JLabel courseLabel = new JLabel(course.getName());
//        labele.add(courseLabel);
//        courseLabel.setFont(new Font("Arial", Font.PLAIN, 16));  // Set font size for the label
//        CourseList.add(courseLabel);  // Add the label to the CourseList panel
//        
//    }
//    
//    
//    
//    
//    
//    // Refresh the UI to display the added components
//    CourseList.revalidate();
//    CourseList.repaint();
//    }
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")

/*
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        CourseList = new javax.swing.JPanel();
        NewMapelPanel = new javax.swing.JPanel();
        NMapel = new javax.swing.JTextField();
        Deskripsi = new javax.swing.JTextField();
        AddMapel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        KMapel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(160, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 440));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 60, 200, 440);

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Wirexam");

        jPanel6.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(551, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 800, 60);

        CourseList.setBackground(new java.awt.Color(255, 255, 255));
        CourseList.setPreferredSize(new java.awt.Dimension(600, 440));

        javax.swing.GroupLayout CourseListLayout = new javax.swing.GroupLayout(CourseList);
        CourseList.setLayout(CourseListLayout);
        CourseListLayout.setHorizontalGroup(
            CourseListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        CourseListLayout.setVerticalGroup(
            CourseListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPanel2.add(CourseList);
        CourseList.setBounds(200, 60, 310, 440);

        NewMapelPanel.setBackground(new java.awt.Color(51, 51, 255));

        NMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NMapelActionPerformed(evt);
            }
        });

        Deskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeskripsiActionPerformed(evt);
            }
        });

        AddMapel.setText("Submit");
        AddMapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMapel(evt);
            }
        });

        jLabel2.setText("Nama Mapel");

        jLabel3.setText("Deskripsi");

        KMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KMapelActionPerformed(evt);
            }
        });

        jLabel4.setText("Kode Mapel");

        javax.swing.GroupLayout NewMapelPanelLayout = new javax.swing.GroupLayout(NewMapelPanel);
        NewMapelPanel.setLayout(NewMapelPanelLayout);
        NewMapelPanelLayout.setHorizontalGroup(
            NewMapelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewMapelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewMapelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Deskripsi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NMapel)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KMapel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NewMapelPanelLayout.createSequentialGroup()
                        .addComponent(AddMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );
        NewMapelPanelLayout.setVerticalGroup(
            NewMapelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewMapelPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Deskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(NewMapelPanel);
        NewMapelPanel.setBounds(510, 60, 293, 440);
        NewMapelPanel.getAccessibleContext().setAccessibleParent(NewMapelPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NMapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NMapelActionPerformed

    private void DeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeskripsiActionPerformed

    private void KMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KMapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KMapelActionPerformed

    private void AddMapel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMapel
        String kode = KMapel.getText();
        String name = NMapel.getText();
        String description = Deskripsi.getText();
        
        if(Course.addMatkul(kode, name, description)) {
            JOptionPane.showMessageDialog(null, "Berhasil Menambah Mapel");
            populateCourseList();
        } else {
            JOptionPane.showMessageDialog(null, "Gagal Menambah Mapel");
        }
    }//GEN-LAST:event_AddMapel

    /**
     * @param args the command line arguments
     */
/*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
/*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMapel;
    private javax.swing.JPanel CourseList;
    private javax.swing.JTextField Deskripsi;
    private javax.swing.JTextField KMapel;
    private javax.swing.JTextField NMapel;
    private javax.swing.JPanel NewMapelPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
*/